### ISSUE TITLE
Using globalfilters with EDMX

### ISSUE THREAD

**Issue by farreachchad** [jbogard/EntityFramework.Filters#14]
OnModelCreating is not available to override when using EDMX. Any thoughts on how to get around this?

**Comment by chadash** [comment]
hello farreachchad!
Are you succeed with using the filtering by a DatabaseFirst Approach?
Can you give some example of how to initialize the filter?
thank you

**Comment by farreachchad** [comment]
We were not able to get this to work.

**Comment by chadash** [comment]
thank you for your answer
