### ISSUE TITLE
Asp.Net Core

### ISSUE THREAD

**Issue by ranouf** [jbogard/EntityFramework.Filters#29]
Hi,

Do you plan to put it on Asp.Net Core?

Cedric

**Comment by jbogard** [comment]
No, not really, EF Core is going to support it OOTB

**Comment by ranouf** [comment]
Ok, Too bad, I need to use it now, but I dont find a solution in EF Core currently. I will try to find something else.
Thanks

**Comment by jbogard** [comment]
Eh?

https://blogs.msdn.microsoft.com/dotnet/2017/05/12/announcing-ef-core-2-0-preview-1/

Global query filters.

**Comment by ranouf** [comment]
It seems to be only available in Preview Version only, I can t use it for a website in production :(

**Comment by jbogard** [comment]
All of EF Core is a preview version ;)

But yeah, no plans to create something that exists in the product already.
You can't use something with a go-live license?

**Comment by ranouf** [comment]
go-live license, I dont know what is it.

I use soft delete for my website, so when I do an Include, there is still the deleted stuff. I expected to get a solution before the end of the project, but after 3 months there is still no solution available on stable version, So currently I dont know what I can do ...

**Comment by jbogard** [comment]
Go-live means you can use it in production and be supported by MS.

**Comment by ranouf** [comment]
The problem is more about me who are not confortable to use a preview version on a production website.
