### ISSUE TITLE
Parameter filters values cached between context instances 

### ISSUE THREAD

**Issue by xabikos** [jbogard/EntityFramework.Filters#8]
In continuation of the discussion here (http://lostechies.com/jimmybogard/2014/05/29/missing-ef-feature-workarounds-filters/#comment-1457366765) when we set a value in a filter parameter this value cached and never change even if we create different DbContext instances. This happens probably because in the implementation of filters we use the FilterInterceptor which Implements IDbCommandTreeInterceptor and the execution of this method happens only once for query commands and then this is cached. So for example in soft delete functionality that Miller present in TechEd video this works fine as we filter against a hard coded boolean value. In case we want to filter on tenant Id then we always get back the results for the first tenant. Pay attention to the remarks in the documentation here https://entityframework.codeplex.com/SourceControl/latest#src/EntityFramework/Infrastructure/Interception/IDbCommandTreeInterceptor.cs

**Comment by erichexter** [comment]
@jbogard @jcachat  So where does this net out? Does https://github.com/jcachat/EntityFramework.DynamicFilters replace this library?  If so, how about updating the readme, to say this was a prototype and link to DynamicFilters?
